language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - npm run build

stages:
  - prepare
  - compile
  - test
  - reports


jobs:
  include:
    - stage: prepare
      name: Welcome to jdn
      script:
        - echo ------------------- WELCOME TO JDN ----------------------
        - node --version #it is helpful
        - npm install

    - stage: compile
      name: Compile jdn code
      script:
        - npm run webpack

deploy:
  provider: releases
  api_key: "aa60564706663c431d907927f971c07a2a1815a2"
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true

after_failure:
  - echo "Build was failed"
after_success:
  - echo "Build was successful"

# extra time during long builds
install:
  - travis_wait
